Code review on bash_install_{app,jar,tar,zip}

diff --git a/bin/bash_install_app b/bin/bash_install_app
--- a/bin/bash_install_app
+++ b/bin/bash_install_app
@@ -5,7 +5,7 @@ function __bash_install_app_help(){
   echo "Downloads URL, save onto FILE, copy into FOLDER, creates SYMLINKS under BIN to SUBFOLDER."
 }
 
-function __bash_install_app() {
+function __bash_install_app_worker() {
   which wget >/dev/null 2>&1 || apt+ install wget
 
   [[ $# -lt 3 ]] && __bash_install_app_help && return 1
@@ -35,7 +35,7 @@ function __bash_install_app() {
   fi
 
   # validate existing archive
-  [[ ! -z "${archive}" ]] && [[ ! -s "${archive}" ]] && rm "${archive}" && local archive=""
+  [[ ! -s "${archive}" ]] && [[ ! -s "${archive}" ]] && rm "${archive}" && local archive=""
 
   # download archive
   if [[ -z "${archive}" ]]; then
@@ -59,6 +59,23 @@ function __bash_install_app() {
             return 0
         fi
 }
+
+function __bash_install_app_logger() (
+  set -x
+  __bash_install_app_worker $@ 2> ${log}
+)    
+
+function __bash_install_app() {
+  local log=$(mktemp -t bash_install_app.XXX.log)
+  echo "INFO: See installation log at: ${log}"
+  set +e
+  __bash_install_app_logger $@ 2> ${log}
+  local errno=$?
+  set -e
+  [[ ${errno} -eq 0 ]] || echo "ERROR: errno=${errno} :: installation failed."
+  return ${errno}  
+}
+
 
 if [ $_ != $0 ]; then
   # echo "Script is being sourced: list all functions"
diff --git a/bin/bash_install_jar b/bin/bash_install_jar
--- a/bin/bash_install_jar
+++ b/bin/bash_install_jar
@@ -16,7 +16,7 @@ EOD
   chmod ugo+x "${launcher}"
 }
 
-function __bash_install_jar() {
+function __bash_install_jar_worker() {
   which wget >/dev/null 2>&1 || apt+ install wget
 
   [[ $# -lt 3 ]] && __bash_install_jar_help && return 1
@@ -48,12 +48,12 @@ function __bash_install_jar() {
   which unzip >/dev/null 2>&1 || apt+ install zip unzip
 
   # validate existing archive
-  [[ ! -z "${archive}" ]] && [[ ! $(unzip -t "${archive}" > /dev/null 2>&1) ]] && rm "${archive}" && local archive=""
+  [[ ! -s "${archive}" ]] && [[ ! $(unzip -t "${archive}" > /dev/null 2>&1) ]] && rm "${archive}" && local archive=""
 
   # download archive
   if [[ -z "${archive}" ]]; then
     local archive="${DOWNLOADS}/${file}"
-    wget -q "$url" -O "${archive}"
+    wget -nv "$url" -O "${archive}"
   fi
 
   # apply relative folder to base path if necessary
@@ -65,7 +65,7 @@ function __bash_install_jar() {
         if [[ ! -z "${symlinks}" ]] ;then
           echo "${symlinks}" | tr ',' '\n' | head -1 | \
             while read symlink ;do
-              [[ ! -L "${bin}/${symlink}" ]] || rm "${bin}/${symlink}" && \
+              [[ ! -e "${bin}/${symlink}" ]] || rm "${bin}/${symlink}" && \
                 __bash_install_jar_launcher "${folder}/${subfolder}/${symlink}" "${folder}/${subfolder}/${file}" && \
                 ln -s "${folder}/${subfolder}/${symlink}" "${bin}/${symlink}" && echo "${bin}/${symlink}"
             done
@@ -73,6 +73,23 @@ function __bash_install_jar() {
             return 0
         fi
 }
+
+function __bash_install_jar_logger() (
+  set -x
+  __bash_install_jar_worker $@ 2> ${log}
+)    
+
+function __bash_install_jar() {
+  local log=$(mktemp -t bash_install_jar.XXX.log)
+  echo "INFO: See installation log at: ${log}"
+  set +e
+  __bash_install_jar_logger $@ 2> ${log}
+  local errno=$?
+  set -e
+  [[ ${errno} -eq 0 ]] || echo "ERROR: errno=${errno} :: installation failed."
+  return ${errno}  
+}
+
 
 if [ $_ != $0 ]; then
   # echo "Script is being sourced: list all functions"
diff --git a/bin/bash_install_tar b/bin/bash_install_tar
--- a/bin/bash_install_tar
+++ b/bin/bash_install_tar
@@ -5,7 +5,8 @@ function __bash_install_tar_help(){
   echo "Downloads URL, save onto FILE, tar extract into FOLDER, creates SYMLINKS under BIN to SUBFOLDER."
 }
 
-function __bash_install_tar() {
+function __bash_install_tar_worker() {
+  set -x
   which wget >/dev/null 2>&1 || apt+ install wget
 
   [[ $# -lt 3 ]] && __bash_install_tar_help && return 1
@@ -40,7 +41,7 @@ function __bash_install_tar() {
   which xz >/dev/null 2>&1 || apt+ install xz
 
   # validate existing archive
-  [[ ! -z "${archive}" ]] && [[ ! $(tar -tf "${archive}" > /dev/null 2>&1) ]] && rm "${archive}" && local archive=""
+  [[ ! -s "${archive}" ]] && [[ ! $(tar -tf "${archive}" > /dev/null 2>&1) ]] && rm "${archive}" && local archive=""
 
   # download archive
   if [[ -z "${archive}" ]]; then
@@ -63,6 +64,23 @@ function __bash_install_tar() {
           return 0
       fi
 }
+
+function __bash_install_tar_logger() (
+  set -x
+  __bash_install_tar_worker $@ 2> ${log}
+)    
+
+function __bash_install_tar() {
+  local log=$(mktemp -t bash_install_tar.XXX.log)
+  echo "INFO: See installation log at: ${log}"
+  set +e
+  __bash_install_tar_logger $@ 2> ${log}
+  local errno=$?
+  set -e
+  [[ ${errno} -eq 0 ]] || echo "ERROR: errno=${errno} :: installation failed."
+  return ${errno}  
+}
+
 
 if [ $_ != $0 ]; then
   # echo "Script is being sourced: list all functions"
diff --git a/bin/bash_install_zip b/bin/bash_install_zip
--- a/bin/bash_install_zip
+++ b/bin/bash_install_zip
@@ -5,7 +5,7 @@ function __bash_install_zip_help(){
   echo "Downloads URL, save onto FILE, tar extract into FOLDER, creates SYMLINKS under BIN to SUBFOLDER."
 }
 
-function __bash_install_zip() {
+function __bash_install_zip_worker() {
   which wget >/dev/null 2>&1 || apt+ install wget
 
   [[ $# -lt 3 ]] && __bash_install_zip_help && return 1
@@ -40,7 +40,7 @@ function __bash_install_zip() {
   which unzip >/dev/null 2>&1 || apt+ install zip unzip
 
   # validate existing archive
-  [[ ! -z "${archive}" ]] && [[ ! $(unzip -t "${archive}" > /dev/null 2>&1) ]] && rm "${archive}" && local archive=""
+  [[ ! -s "${archive}" ]] && [[ ! $(unzip -t "${archive}" > /dev/null 2>&1) ]] && rm "${archive}" && local archive=""
 
   # download archive
   if [[ -z "${archive}" ]]; then
@@ -63,6 +63,23 @@ function __bash_install_zip() {
           return 0
       fi
 }
+
+function __bash_install_zip_logger() (
+  set -x
+  __bash_install_zip_worker $@ 2> ${log}
+)    
+
+function __bash_install_zip() {
+  local log=$(mktemp -t bash_install_zip.XXX.log)
+  echo "INFO: See installation log at: ${log}"
+  set +e
+  __bash_install_zip_logger $@ 2> ${log}
+  local errno=$?
+  set -e
+  [[ ${errno} -eq 0 ]] || echo "ERROR: errno=${errno} :: installation failed."
+  return ${errno}  
+}
+
 
 if [ $_ != $0 ]; then
   # echo "Script is being sourced: list all functions"
