Code review: 1. Review bash_install_app, bash_install_tar, bash_install_zip and bash_install_jar; 2. Installation procedures which employ such functions; 3. Fix typos near calls to uname and tr; 4. Rename some functions for better ergonomics.

diff --git a/bin/install_dhall b/bin/install_dhall
--- a/bin/install_dhall
+++ b/bin/install_dhall
@@ -1,198 +1,92 @@
 #!/bin/bash -eu
 
+function __install_dhall_binaries() {
+  local name=${1}
+  local releases="${2}"
+  local arch="${3}"
+  local var="${4}"
+  local package="${5}"
+  local version="${6}"
+  local symlinks="${7}"
 
-function __install_dhall_activator() {
-  local self=$(readlink -f "${BASH_SOURCE[0]}")
-  local dir=$(dirname $self)
+  local file=${name}-${version}-${arch}.tar.bz2
+  local url=${releases}/download/${package}/${file}
+  local folder=${name}-${package}-${version}
+  if [[ -z "${symlinks}" ]] ;then
+      local subfolder=
+      local bin=
+  else
+      local subfolder=bin
+      local bin="${VIRTUAL_ENV:-${HOME}/.local/share/bash-scripts}/bin"
+  fi
 
-  local activator="${1}"
-  local version="${2}"
+  "${dir}"/bash_install_tar "${url}" "${file}" "${folder}" "${symlinks}" "${bin}" "${subfolder}" "--" "--strip-components=1"
 
+  local config="${VIRTUAL_ENV:-${HOME}/.local/share/bash-scripts}"/postactivate/postactivate.d/271-${name}.sh
   [[ ! -d $(dirname "${config}") ]] && mkdir -p $(dirname "${config}")
   cat <<EOD > "${config}"
 #!/bin/bash
 
-export DHALL_VERSION=${version}
-export DHALL_ARCH=\${DHALL_ARCH:-x86_64-linux}
-export DHALL_HOME=\${TOOLS_HOME:=\$HOME/tools}/dhall-v\${DHALL_VERSION}-\${DHALL_ARCH}/bin
-
-export PATH=\${DHALL_HOME}:\${PATH}
+export DHALL_PACKAGE=${package}
+export ${var}_VERSION=${version}
+export ${var}_HOME=\${TOOLS_HOME:=\$HOME/tools}/${folder}
 EOD
   chmod ugo+x "${config}"
   echo "${config}"
-}    
-
-function __install_dhall_compiler_binaries() {
-  local self=$(readlink -f "${BASH_SOURCE[0]}")
-  local dir=$(dirname $self)
-
-  which wget >/dev/null 2>&1 || apt+ install wget
-
-  local latest=https://github.com/dhall-lang/dhall-haskell/releases/latest
-  local version=$(wget -q -SO- -T 5 -t 1 "${latest}" 2>/dev/null | fgrep location: | cut -d' ' -f2 | sed -E 's|.*\/v(.*)|\1|')
-  local version=${version:-"1.38.0"}
-  local version=${1:-"${version}"}
-
-  ##FIXME: local arch=${2:-"$DHALL_ARCH"}
-  local arch=${arch:-"x86_64-linux"}
-
-  local file=dhall-${version}-${arch}.tar.bz2
-  local url=https://github.com/dhall-lang/dhall-haskell/releases/download/${version}/${file}
-  local folder=dhall-v${version}-${arch}
-  local symlink=dhall
-
-  local config="${VIRTUAL_ENV:-${HOME}/.local/share/bash-scripts}"/postactivate/postactivate.d/271-dhall.sh
-   __install_dhall_activator "${config}" "${version}"
-
-  "${dir}"/bash_install_tar "${url}" "${file}" "${folder}" "${symlink}"
-}
-
-function __install_dhall_lsp_binaries() {
-  local self=$(readlink -f "${BASH_SOURCE[0]}")
-  local dir=$(dirname $self)
-
-  which wget >/dev/null 2>&1 || apt+ install wget
-
-  local latest=https://github.com/dhall-lang/dhall-haskell/releases/latest
-  local version=$(wget -q -SO- -T 5 -t 1 "${latest}" 2>/dev/null | fgrep location: | cut -d' ' -f2 | sed -E 's|.*\/v(.*)|\1|')
-  local version=${version:-"1.38.0"}
-  local version=${1:-"${version}"}
-
-  ##FIXME: local vtool=${2:-"$DHALL_LSP_VERSION"}
-  local vtool=${vtool:-"1.0.13"}
-
-  ##FIXME: local arch=${3:-"$DHALL_ARCH"}
-  local arch=${arch:-"x86_64-linux"}
-
-  local file=dhall-lsp-server-${vtool}-${arch}.tar.bz2
-  local url=https://github.com/dhall-lang/dhall-haskell/releases/download/${version}/${file}
-  local folder=dhall-v${version}-${arch}
-  local symlink=dhall
-
-  "${dir}"/bash_install_tar "${url}" "${file}" "${folder}" "${symlink}"
-}
-
-function __install_dhall_json_binaries() {
-  local self=$(readlink -f "${BASH_SOURCE[0]}")
-  local dir=$(dirname $self)
-
-  which wget >/dev/null 2>&1 || apt+ install wget
-
-  local latest=https://github.com/dhall-lang/dhall-haskell/releases/latest
-  local version=$(wget -q -SO- -T 5 -t 1 "${latest}" 2>/dev/null | fgrep location: | cut -d' ' -f2 | sed -E 's|.*\/v(.*)|\1|')
-  local version=${version:-"1.38.0"}
-  local version=${1:-"${version}"}
-
-  ##FIXME: local vtool=${2:-"$DHALL_JSON_VERSION"}
-  local vtool=${vtool:-"1.7.5"}
-
-  ##FIXME: local arch=${3:-"$DHALL_ARCH"}
-  local arch=${arch:-"x86_64-linux"}
-
-  local file=dhall-json-${vtool}-${arch}.tar.bz2
-  local url=https://github.com/dhall-lang/dhall-haskell/releases/download/${version}/${file}
-  local folder=dhall-v${version}-${arch}
-  local symlink=dhall
-
-  "${dir}"/bash_install_tar "${url}" "${file}" "${folder}" "${symlink}"
-}
-
-function __install_dhall_yaml_binaries() {
-  local self=$(readlink -f "${BASH_SOURCE[0]}")
-  local dir=$(dirname $self)
-
-  which wget >/dev/null 2>&1 || apt+ install wget
-
-  local latest=https://github.com/dhall-lang/dhall-haskell/releases/latest
-  local version=$(wget -q -SO- -T 5 -t 1 "${latest}" 2>/dev/null | fgrep location: | cut -d' ' -f2 | sed -E 's|.*\/v(.*)|\1|')
-  local version=${version:-"1.38.0"}
-  local version=${1:-"${version}"}
-
-  ##FIXME: local vtool=${2:-"$DHALL_YAML_VERSION"}
-  local vtool=${vtool:-"1.2.5"}
-
-  ##FIXME: local arch=${3:-"$DHALL_ARCH"}
-  local arch=${arch:-"x86_64-linux"}
-
-  local file=dhall-yaml-${vtool}-${arch}.tar.bz2
-  local url=https://github.com/dhall-lang/dhall-haskell/releases/download/${version}/${file}
-  local folder=dhall-v${version}-${arch}
-  local symlink=dhall
-
-  "${dir}"/bash_install_tar "${url}" "${file}" "${folder}" "${symlink}"
-}
-
-function __install_dhall_bash_binaries() {
-  local self=$(readlink -f "${BASH_SOURCE[0]}")
-  local dir=$(dirname $self)
-
-  which wget >/dev/null 2>&1 || apt+ install wget
-
-  local latest=https://github.com/dhall-lang/dhall-haskell/releases/latest
-  local version=$(wget -q -SO- -T 5 -t 1 "${latest}" 2>/dev/null | fgrep location: | cut -d' ' -f2 | sed -E 's|.*\/v(.*)|\1|')
-  local version=${version:-"1.38.0"}
-  local version=${1:-"${version}"}
-
-  ##FIXME: local vtool=${2:-"$DHALL_BASH_VERSION"}
-  local vtool=${vtool:-"1.0.36"}
-
-  ##FIXME: local arch=${3:-"$DHALL_ARCH"}
-  local arch=${arch:-"x86_64-linux"}
-
-  local file=dhall-bash-${vtool}-${arch}.tar.bz2
-  local url=https://github.com/dhall-lang/dhall-haskell/releases/download/${version}/${file}
-  local folder=dhall-v${version}-${arch}
-  local symlink=dhall
-
-  "${dir}"/bash_install_tar "${url}" "${file}" "${folder}" "${symlink}"
-}
-
-function __install_dhall_nix_binaries() {
-  local self=$(readlink -f "${BASH_SOURCE[0]}")
-  local dir=$(dirname $self)
-
-  which wget >/dev/null 2>&1 || apt+ install wget
-
-  local latest=https://github.com/dhall-lang/dhall-haskell/releases/latest
-  local version=$(wget -q -SO- -T 5 -t 1 "${latest}" 2>/dev/null | fgrep location: | cut -d' ' -f2 | sed -E 's|.*\/v(.*)|\1|')
-  local version=${version:-"1.38.0"}
-  local version=${1:-"${version}"}
-
-  ##FIXME: local vtool=${2:-"$DHALL_NIX_VERSION"}
-  local vtool=${vtool:-"1.1.20"}
-
-  ##FIXME: local arch=${3:-"$DHALL_ARCH"}
-  local arch=${arch:-"x86_64-linux"}
-
-  local file=dhall-nix-${vtool}-${arch}.tar.bz2
-  local url=https://github.com/dhall-lang/dhall-haskell/releases/download/${version}/${file}
-  local folder=dhall-v${version}-${arch}
-  local symlink=dhall
-
-  "${dir}"/bash_install_tar "${url}" "${file}" "${folder}" "${symlink}"
 }
 
 function __install_dhall() {
-  __install_dhall_compiler_binaries "$@" && \
-  __install_dhall_lsp_binaries "$@" && \
-  __install_dhall_json_binaries "$@" && \
-  __install_dhall_yaml_binaries "$@" && \
-  __install_dhall_bash_binaries "$@" && \
-  __install_dhall_nix_binaries "$@"
+  local self=$(readlink -f "${BASH_SOURCE[0]}")
+  local dir=$(dirname $self)
+
+  which curl >/dev/null 2>&1 || apt+ install wget
+
+  local name=dall
+  local releases=https://github.com/dhall-lang/dhall-haskell/releases
+  local latest=${releases}/latest
+  local latest="$(curl -I ${latest} 2>/dev/null | fgrep location: | tr -d '[:cntrl:]' | cut -d' ' -f2 | sed -E 's|.*\/(.*)$|\1|')"
+  echo "${name}: latest version: ${latest}" 1>&2
+  local default="${DALL_VERSION:-${latest:-1.41.1}}"
+  local version="${1:-${default}}"
+  echo "${name}: installing version: ${version}" 1>&2
+
+  local hwarch=$(uname -m | tr '[:upper:]' '[:lower:]')
+  case "${hwarch}" in
+    x86_64) ;;
+    *) echo "ERROR: hardware platform is not supported: ${hwarch}" ; return 1 ;;
+  esac
+  local osarch=$(uname -s | tr '[:upper:]' '[:lower:]')
+  case "${osarch}" in
+      linux) ;;
+      darwin) osarch=macos ;;
+      *) echo "ERROR: software platform is not supported: ${osarch}" ; return 1 ;;
+  esac
+  local arch=${hwarch}-${osarch}
+
+  local dhall_version=${version}
+  __install_dhall_binaries "dhall" "${releases}" "${arch}" "DHALL" "${dhall_version}" "${version}" "dhall"
+  
+  for name in bash csv docs json lsp-server nix nixpkgs openapi toml yaml ;do
+    #ocal NAME=
+    local NAME="DHALL_$(echo "${name}" | tr '[:lower:]-' '[:upper:]_')"
+    local VAR="${NAME}_VERSION"
+    local cabal=https://raw.githubusercontent.com/dhall-lang/dhall-haskell/${dhall_version}/dhall-${name}/dhall-${name}.cabal
+    local latest="$(curl ${cabal} 2>/dev/null | head -10 | grep -E '^Version: ' | tr -d ' ' | cut -d: -f2)"
+    echo "${name}: latest version: ${latest}" 1>&2
+    local default="${!VAR:-${latest:-1.41.1}}"
+    local version="${1:-${default}}"
+    echo "${name}: installing version: ${version}" 1>&2
+
+    local symlinks="$(curl ${cabal} 2>/dev/null | grep -E '^Executable ' | cut -d' ' -f2 | tr '\n' ',' | sed -E 's/,$//')"
+
+    __install_dhall_binaries "dhall-${name}" "${releases}" "${arch}" "${NAME}" "${dhall_version}" "${version}" "${symlinks}"
+  done
 }
 
 
 if [ $_ != $0 ]; then
   # echo "Script is being sourced: list all functions"
   grep -E "^function [a-zA-Z0-9]" $(readlink -f "${BASH_SOURCE[0]}") | cut -d' ' -f2 | sed 's/()//'
-else
-  # echo "Script is a subshell: execute last function"
-  $(grep -E "^function __" $(readlink -f "${BASH_SOURCE[0]}") | cut -d' ' -f2  | sed 's/()//' | tail -1) "$@"
-fi
-XXXX
-if [ $_ != $0 ]; then
-  # echo "Script is being sourced: list all functions"
-  grep -E "^function __" $(readlink -f "${BASH_SOURCE[0]}") | cut -d' ' -f2 | sed 's/()//'
 else
   # echo "Script is a subshell: execute last function"
   $(grep -E "^function __" $(readlink -f "${BASH_SOURCE[0]}") | cut -d' ' -f2  | sed 's/()//' | tail -1) "$@"
diff --git a/bin/install_java b/bin/install_java
--- a/bin/install_java
+++ b/bin/install_java
@@ -1,102 +1,97 @@
 #!/bin/bash -eu
 
-function __install_java_activator {
-  local self=$(readlink -f "${BASH_SOURCE[0]}")
-  local dir=$(dirname $self)
+function install_java_binaries {
+  self=$(readlink -f "${BASH_SOURCE[0]}")
+  dir=$(dirname $self)
 
-  local activator="${1}"
-  local version="${2}"
+  local version=${version:-"8"}
+  local version=${1:-"${version}"}
+
+  local name=jdk
+  if [[ $version =~ ^8(\.*)? ]] ;then
+    local jvm=8
+    local tag=8u292
+    local build=b10
+    local version=${tag}${build}
+    local file=OpenJDK8U-jdk_x64_linux_hotspot_${version}.tar.gz
+    local url=https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk${tag}-${build}/${file}
+    local folder=${name}${tag}-${build}-jdk
+  elif [[ $version =~ ^11(\.*)? ]] ;then
+    local jvm=11
+    local tag=${jvm}.0.11
+    local build=9
+    local version=${tag}_${build}
+    local file=OpenJDK${jvm}U-jdk_x64_linux_hotspot_${version}.tar.gz
+    local url=https://github.com/AdoptOpenJDK/openjdk${jvm}-binaries/releases/download/jdk-${tag}%2B${build}/${file}
+    local folder=${name}-${jvm}
+  elif [[ $version =~ ^12(\.*)? ]] ;then
+    local jvm=12
+    local tag=${jvm}.0.2
+    local build=10
+    local version=${tag}_${build}
+    local file=OpenJDK${jvm}U-jdk_x64_linux_hotspot_${version}.tar.gz
+    local url=https://github.com/AdoptOpenJDK/openjdk${jvm}-binaries/releases/download/jdk-${tag}%2B${build}/${file}
+    local folder=${name}-${jvm}
+  elif [[ $version =~ ^13(\.*)? ]] ;then
+    local jvm=13
+    local tag=${jvm}.0.2
+    local build=8
+    local version=${tag}_${build}
+    local file=OpenJDK${jvm}U-jdk_x64_linux_hotspot_${version}.tar.gz
+    local url=https://github.com/AdoptOpenJDK/openjdk${jvm}-binaries/releases/download/jdk-${tag}%2B${build}/${file}
+    local folder=${name}-${jvm}
+  elif [[ $version =~ ^14(\.*)? ]] ;then
+    local jvm=14
+    local tag=${jvm}.0.2
+    local build=12
+    local version=${tag}_${build}
+    local file=OpenJDK${jvm}U-jdk_x64_linux_hotspot_${version}.tar.gz
+    local url=https://github.com/AdoptOpenJDK/openjdk${jvm}-binaries/releases/download/jdk-${tag}%2B${build}/${file}
+    local folder=${name}-${jvm}
+  elif [[ $version =~ ^15(\.*)? ]] ;then
+    local jvm=15
+    local tag=${jvm}.0.2
+    local build=7
+    local version=${tag}_${build}
+    local file=OpenJDK${jvm}U-jdk_x64_linux_hotspot_${version}.tar.gz
+    local url=https://github.com/AdoptOpenJDK/openjdk${jvm}-binaries/releases/download/jdk-${tag}%2B${build}/${file}
+    local folder=${name}-${jvm}
+  elif [[ $version =~ ^16(\.*)? ]] ;then
+    local jvm=16
+    local tag=${jvm}.0.1
+    local build=9
+    local version=${tag}_${build}
+    local file=OpenJDK${jvm}U-jdk_x64_linux_hotspot_${version}.tar.gz
+    local url=https://github.com/AdoptOpenJDK/openjdk${jvm}-binaries/releases/download/jdk-${tag}%2B${build}/${file}
+    local folder=${name}-${jvm}
+  else
+    echo "ERROR: Unsupported Java version $JAVA_VERSION"
+    echo 'INFO: Supported JDK versions are: 1.8.*, 11.*, 12.*, 13.*, 14.*, 15.*, 16.*'
+    return 1
+  fi
+  local symlinks=--
+ #local bin="${VIRTUAL_ENV:-${HOME}/.local/share/bash-scripts}/bin"
+  local bin=--
+  local subfolder=--
+
+  echo Latest version: "(not detected)" 1>&2
+  echo Installing version: "${version}" 1>&2
+
+  "${dir}"/bash_install_tar "${url}" "${file}" "${folder}" "${symlinks}" "${bin}" "${subfolder}" "--strip-components=1"
+
+  local config="${VIRTUAL_ENV:-${HOME}/.local/share/bash-scripts}"/postactivate/postactivate.d/300-java.sh
   local major=$(echo ${version} | cut -d. -f1)
-
   [[ ! -d $(dirname "${config}") ]] && mkdir -p $(dirname "${config}")
   cat <<EOD > "${config}"
 #!/bin/bash
 
 export JAVA_VERSION=${version}
 export JAVA_VERSION_MAJOR=${major}
-export JAVA_HOME=\${TOOLS_HOME:=\$HOME/tools}/jdk\${JAVA_VERSION_MAJOR}
-
+export JAVA_HOME=\${TOOLS_HOME:=\$HOME/tools}/${folder}
 export PATH=\${JAVA_HOME}/bin:\${PATH}
 EOD
   chmod ugo+x "${config}"
   echo "${config}"
-}    
-
-function install_java_binaries {
-  self=$(readlink -f "${BASH_SOURCE[0]}")
-  dir=$(dirname $self)
-
-  which wget >/dev/null 2>&1 || apt+ install wget
-
-  local version=${version:-"8"}
-  local version=${1:-"${version}"}
-  local major=$(echo ${version} | cut -d. -f1)
-
-  if [[ $version =~ ^8(\.*)? ]] ;then
-    local tag=8u292
-    local build=b10
-    local file=OpenJDK8U-jdk_x64_linux_hotspot_${tag}${build}.tar.gz
-    local url=https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk${tag}-${build}/${file}
-    local folder=jdk${tag}-${build}-jdk
-    local symlink=jdk8
-  elif [[ $version =~ ^11(\.*)? ]] ;then
-    local jvm=11
-    local tag=${jvm}.0.11
-    local build=9
-    local file=OpenJDK${jvm}U-jdk_x64_linux_hotspot_${tag}_${build}.tar.gz
-    local url=https://github.com/AdoptOpenJDK/openjdk${jvm}-binaries/releases/download/jdk-${tag}%2B${build}/${file}
-    local folder=jdk-${jvm}
-    local symlink=jdk${jvm}
-  elif [[ $version =~ ^12(\.*)? ]] ;then
-    local jvm=12
-    local tag=${jvm}.0.2
-    local build=10
-    local file=OpenJDK${jvm}U-jdk_x64_linux_hotspot_${tag}_${build}.tar.gz
-    local url=https://github.com/AdoptOpenJDK/openjdk${jvm}-binaries/releases/download/jdk-${tag}%2B${build}/${file}
-    local folder=jdk-${jvm}
-    local symlink=jdk${jvm}
-  elif [[ $version =~ ^13(\.*)? ]] ;then
-    local jvm=13
-    local tag=${jvm}.0.2
-    local build=8
-    local file=OpenJDK${jvm}U-jdk_x64_linux_hotspot_${tag}_${build}.tar.gz
-    local url=https://github.com/AdoptOpenJDK/openjdk${jvm}-binaries/releases/download/jdk-${tag}%2B${build}/${file}
-    local folder=jdk-${jvm}
-    local symlink=jdk${jvm}
-  elif [[ $version =~ ^14(\.*)? ]] ;then
-    local jvm=14
-    local tag=${jvm}.0.2
-    local build=12
-    local file=OpenJDK${jvm}U-jdk_x64_linux_hotspot_${tag}_${build}.tar.gz
-    local url=https://github.com/AdoptOpenJDK/openjdk${jvm}-binaries/releases/download/jdk-${tag}%2B${build}/${file}
-    local folder=jdk-${jvm}
-    local symlink=jdk${jvm}
-  elif [[ $version =~ ^15(\.*)? ]] ;then
-    local jvm=15
-    local tag=${jvm}.0.2
-    local build=7
-    local file=OpenJDK${jvm}U-jdk_x64_linux_hotspot_${tag}_${build}.tar.gz
-    local url=https://github.com/AdoptOpenJDK/openjdk${jvm}-binaries/releases/download/jdk-${tag}%2B${build}/${file}
-    local folder=jdk-${jvm}
-    local symlink=jdk${jvm}
-  elif [[ $version =~ ^16(\.*)? ]] ;then
-    local jvm=16
-    local tag=${jvm}.0.1
-    local build=9
-    local file=OpenJDK${jvm}U-jdk_x64_linux_hotspot_${tag}_${build}.tar.gz
-    local url=https://github.com/AdoptOpenJDK/openjdk${jvm}-binaries/releases/download/jdk-${tag}%2B${build}/${file}
-    local folder=jdk-${jvm}
-    local symlink=jdk${jvm}
-  else
-    echo "ERROR: Unsupported Java version $JAVA_VERSION"
-    echo 'INFO: Supported JDK versions are: 1.8.*, 11.*, 12.*, 13.*, 14.*, 15.*, 16.*'
-    return 1
-  fi
-
-  "${dir}"/bash_install_tar "${url}" "${file}" "${folder}" "${symlink}" "--strip-components=1"
-
-  local config="${VIRTUAL_ENV:-${HOME}/.local/share/bash-scripts}"/postactivate/postactivate.d/300-java.sh
-   __install_java_activator "${config}" "${version}"
 }
 
 function __install_java {
